print("Aj Bautista")
print("Tanza Boac Marinduque")
print("January 1, 2002")
print("Bachelor of science in Information Technology")
print("Second Year College")
print("Playing Basketball")
print("Singing")
print("Playing Online Games")
print("Eating")
print("Traveling")